project:
  render:
    - published-202306-sanou-multiscale_glasso.qmd

title: "Inference of Multiscale Gaussian Graphical Models"
subtitle: ""
author:
  - name: Edmond Sanou
    corresponding: true
    email: doedmond.sanou@univ-evry.fr 
    url: https://desanou.github.io/
    affiliations:
      - name: Université Paris-Saclay, CNRS, Univ Evry, Laboratoire de Mathématiques et Modélisation d'Evry
        url: http://www.math-evry.cnrs.fr/
  - name: Christophe Ambroise
    email: christophe.ambroise@univ-evry.fr
    url: https://cambroise.github.io/
    affiliations:
      - name: Université Paris-Saclay, CNRS, Univ Evry, Laboratoire de Mathématiques et Modélisation d'Evry
        url: http://www.math-evry.cnrs.fr/
  - name: Geneviève Robin
    email: genevievelrobin@gmail.com
    url: https://genevieverobin.wordpress.com/
    affiliations:
      - name: Université Paris-Saclay, CNRS, Univ Evry, Laboratoire de Mathématiques et Modélisation d'Evry
        url: http://www.math-evry.cnrs.fr/
date: 06/28/2023
date-modified: last-modified
abstract: >+
  Gaussian Graphical Models (GGMs) are widely used in high-dimensional data 
  analysis to synthesize the interaction between variables. In many 
  applications, such as genomics or image analysis, graphical models 
  rely on sparsity and clustering to reduce dimensionality and improve 
  performances. This paper explores a slightly different paradigm where 
  clustering is not knowledge-driven but performed simultaneously with 
  the graph inference task. We introduce a novel Multiscale Graphical 
  Lasso (MGLasso) to improve networks interpretability by proposing graphs 
  at different granularity levels. The method estimates clusters through a 
  convex clustering approach --- a relaxation of $k$-means, and hierarchical 
  clustering. The conditional independence graph is simultaneously inferred 
  through a neighborhood selection scheme for undirected graphical models. 
  MGLasso extends and generalizes the sparse group fused lasso problem to 
  undirected graphical models. We use continuation with Nesterov smoothing 
  in a shrinkage-thresholding algorithm (CONESTA) to propose a regularization 
  path of solutions along the group fused Lasso penalty, 
  while the Lasso penalty is kept constant. Extensive 
  experiments on synthetic data compare the performances of our model 
  to state-of-the-art clustering methods and network inference models. 
  Applications to gut microbiome data and poplar's methylation mixed with 
  transcriptomic data are presented.
keywords: [Neighborhood selection, Convex hierarchical clustering, Gaussian graphical models]
citation:
  type: article-journal
  container-title: "Computo"
  doi: "10.57750/1f4p-7955"
  publisher: "French Statistical Society"
  issn: "2824-7795"
google-scholar: true
bibliography: references.bib
github-user: computorg
repo: "published-202306-sanou-multiscale_glasso"
draft: false
published: true
format:
  computo-html:
    fig-width: 8
    fig-height: 6
  computo-pdf: default
execute:
  freeze: auto  # re-render only when source changes
